### ISSUE TITLE
能否根据IP或者实例ID来进行选择性的生成metrics

### ISSUE THREAD

**Issue by feixiaohuijava** [tencentyun/tencentcloud-exporter#1]
哇。没想到腾讯云最近支持了这个exporter。厉害了。
但是感觉这个过滤作用不大。云主机要是有针对性的选择才好。还望支持下。棒棒的~
![image](https://user-images.githubusercontent.com/21102129/65134688-46f49000-da37-11e9-825e-1d70cab06489.png)

**Comment by Himer** [comment]
CVM 云主机 支持属性:

{"Zone", "VpcId", "SubnetId","InstanceName", "InstanceId", "PrivateIpAddress","PublicIpAddress",
 "InstanceChargeType","InstanceType","CreatedTime","ImageId","RenewFlag","SubnetId","CPU","Memory"}

InstanceId 实例ID
PrivateIpAddress 内网ip
PublicIpAddress 外网Ip


eg:
实例ID过滤

tc_namespace: guauga/cvm
 ......
   tc_filters: 
     InstanceId : "ins-hzzzam0w"
 ......


内网IP过滤

tc_namespace: guauga/cvm
 ......
   tc_filters: 
     InstanceId : "172.16.1.127"
 ......
