### ISSUE TITLE
public_clb 负载均衡采集数据问题

### ISSUE THREAD

**Issue by xiaolongc** [tencentyun/tencentcloud-exporter#2]
- tc_namespace: tc/public_clb
   tc_metric_name: Outtraffic
   tc_metric_rename: out_traffic
   tc_labels: [LoadBalancerVip,ProjectId,LoadBalancerName]
   tc_statistics: [max]
   period_seconds: 60
   delay_seconds: 300
   range_seconds: 120
 - tc_namespace: tc/public_clb
   tc_metric_name: Intraffic
   tc_metric_rename: in_traffic
   tc_labels: [LoadBalancerVip,ProjectId,LoadBalancerName]
   tc_statistics: [max]
   period_seconds: 60
   delay_seconds: 300
   range_seconds: 120
 - tc_namespace: tc/public_clb
   tc_metric_name: Connum
   tc_metric_rename: connum
   tc_labels: [LoadBalancerVip,ProjectId,LoadBalancerName]
   tc_statistics: [max]
   period_seconds: 60
   delay_seconds: 300
   range_seconds: 120

公网负载均衡，数据采集与console查询数据、以及https://console.cloud.tencent.com/api/explorer?Product=monitor&Version=2018-07-24&Action=GetMonitorData&SignVersion=在线接口调用不一致

**Comment by Himer** [comment]
你好  能否详细提供一下那个时间段的时间不一致帮忙定位, 最好有下面的信息

1.时间段 如2019-12-31 16:00:00 ~ 2019-12-31 16:05:00
2.字段不一致的表现
如 expoter 采集Intraffic 参数为300   ,而控制台api采集为200
3.api的请求传递的参数

**Comment by Himer** [comment]
我测试了一下  exporter拉取的数据和官网的控制台数据是一样的

export的截图
[https://tfsaastest-1258798060.cos.ap-guangzhou.myqcloud.com/1/version/7/1.png](url)



官方控制台的截图
[https://tfsaastest-1258798060.cos.ap-guangzhou.myqcloud.com/1/version/7/2.png](url)
[https://tfsaastest-1258798060.cos.ap-guangzhou.myqcloud.com/1/version/7/3.png](url)

exporter配置中会对数据进行处理sum  avg和min处理, 如果想要原生的数据可以配置range_seconds为60秒

` - tc_namespace: tc/public_clb
   tc_metric_name: Outtraffic
   tc_metric_rename: out_traffic
   tc_filters: 
     LoadBalancerVip: 134.175.254.48
   tc_labels: [LoadBalancerVip,ProjectId,LoadBalancerName]
   tc_statistics: [max]
   period_seconds: 60
   delay_seconds: 300
   range_seconds: 60
   
 - tc_namespace: tc/public_clb
   tc_metric_name: Intraffic
   tc_metric_rename: in_traffic
   tc_filters: 
     LoadBalancerVip: 134.175.254.48
   tc_labels: [LoadBalancerVip,ProjectId,LoadBalancerName]
   tc_statistics: [max]
   period_seconds: 60
   delay_seconds: 300
   range_seconds: 60
 - tc_namespace: tc/public_clb
   tc_metric_name: Connum
   tc_metric_rename: connum
   tc_filters: 
     LoadBalancerVip: 134.175.254.48
   tc_labels: [LoadBalancerVip,ProjectId,LoadBalancerName]
   tc_statistics: [max]
   period_seconds: 60
   delay_seconds: 300
   range_seconds: 60`
