### ISSUE TITLE
关于 RateLimit 参数的疑问

### ISSUE THREAD

**Issue by AnyISalIn** [tencentyun/tencentcloud-exporter#4]
你好，最在在测试这个项目，我们导入了 66 的CDB(MySQL)的Metric，有六台 CDB，ratelimit 配置为 10 的时候提示 `超过了每秒频率上限`

然后我看了一下代码，按照我的理解 ratelimit 应该是全局的，对  `getMonitorDataByMultipleKeys` 调用做限制，但是我发现不太管用，然后和我看到 `rateLimitCheck` 函数中有一条判断，`if sleepCount > 某个数值` 就不 sleep 了，我的理解是 ratelimit 就不生效了？我尝试把这个参数调整为 1000 秒后，就能够正常拿到数据了。

我对 Go 不太了解，所以请教一下这个参数有什么意义以及 rate limit 是否是全局的？还是只是对单个 goroutine 内生效，谢谢。

**Comment by Himer** [comment]
这个是对cdb调用list接口导致的超频问题, 具体为
====================
rate_limit: 10 #限制此实例接口调用频率, 一秒钟可以有几次监控接口调用

现在的的rate_limit是限制调用监控接口的限速

当添加66个cdb的metric的时候会发起66次的mysql的list接口调用, 这部分还没有重用和限速,  看看加上

**Comment by Himer** [comment]
已经增加list接口的限频

**Comment by AnyISalIn** [comment]
> 已经增加list接口的限频

感谢，更新了代码，有效果，但是偶尔还是会出现

![image](https://user-images.githubusercontent.com/16937838/79703002-6c05f580-82db-11ea-850b-d60e2fc054b6.png)
