### ISSUE TITLE
希望支持使用 tag 过滤实例列表

### ISSUE THREAD

**Issue by LeoQuote** [tencentyun/tencentcloud-exporter#50]
有几个指标是云监控项目就不支持这个维度, 但是exporter 可以在启动的时候用tag 接口请求到实例的列表, 从而生成对应的 dimension , 可以从这个角度实现用 tag 过滤实例列表?

**Comment by zianazhao** [comment]
新的版本v2.15.0已支持，但是tag的key不支持中文字符和特殊字符，欢迎体验
