### ISSUE TITLE
exrea_lables有产品列表吗？

### ISSUE THREAD

**Issue by lixjofgithub** [tencentyun/tencentcloud-exporter#51]
如项获取CVM的IP信息作为label应该如何填写？

**Comment by zianazhao** [comment]
在README的特殊说明中有指导
extra_labels
每个导出metric的labels还额外上报实例对应的字段信息, 实例可选的字段列表可从对应产品文档查询, 如mongo实例支持的字段可从[实例查询api文档](https://cloud.tencent.com/document/product/240/38568) 获取, 目前只支持str、int类型的字段

**Comment by zianazhao** [comment]
例如根据需求填写：IPv6Addresses、PublicIpAddresses、PrivateIpAddresses
