### ISSUE TITLE
经常遇到抓取超时的问题，如何正确排查

### ISSUE THREAD

**Issue by LeoQuote** [tencentyun/tencentcloud-exporter#53]
把一个exporter部署到k8s 内部了，用prometheus进行抓取，偶尔就会遇到抓取超时的，自己去抓也偶尔超时，而且响应时间都很规律，都接近30的倍数，30s，60s，之类的

有没有可能是请求腾讯云的时候超时了，过了30s重试？或者网关重试导致的？如果是这种情况，sdk会打印对应的日志吗？ 我应该如何排查？

**Comment by NeilyoSH** [comment]
如果是 prometheus 抓取job超时,
在job参数中, 增加抓取间隔和超时时间
scrape_interval: 1m
scrape_timeout: 1m


如果是抓取腾讯云这个job超时, 你可以看exporter 输出的日志定位问题.

**Comment by LeoQuote** [comment]
我们最近找了客服发现是 NAT 的出带宽打满了, 如果有遇到类似问题的可以从这个方向来排查
